# Generated by Django 4.2.6 on 2023-11-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_bids_number_of_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bids",
            name="highest_bid",
        ),
        migrations.RemoveField(
            model_name="bids",
            name="number_of_bid",
        ),
        migrations.RemoveField(
            model_name="bids",
            name="object",
        ),
        migrations.AddField(
            model_name="bids",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="auctions.listing",
            ),
        ),
    ]
