# Generated by Django 4.2.6 on 2023-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_remove_bids_highest_bid_remove_bids_number_of_bid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="highest_bid",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bids",
            name="number_of_bid",
            field=models.IntegerField(default=0),
        ),
    ]
