# Generated by Django 5.0 on 2024-01-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
