# Generated by Django 5.0 on 2024-01-05 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_posts_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="user_liking",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
