# Generated by Django 5.0 on 2024-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_posts_user_liking"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.IntegerField(default=0),
        ),
    ]
