# Generated by Django 5.0 on 2024-01-06 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_user_followers_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="number_of_followers",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
