# Generated by Django 5.0 on 2024-01-06 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_user_number_of_followers_remove_user_followers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="number_of_following",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
